### PR TITLE
Update to current Angular version

### PR DESCRIPTION
**Pull request by kylecordes**
Partial PR - Not working. Awaiting fuse-box fix:

https://github.com/fuse-box/fuse-box/issues/324

My suggestion is to set aside this fix or other Angular work until the above is fixed. Material and other Angular related packages generally need tooling to follow normal Node module resolution.
I'm surprised it hasn't been a problem with other uses of fuse-box.

### CODE REVIEW

**Comment by nchanged** [comment]
Please, try this version: `fuse-box@2.1.0-beta.7`

**Comment by nchanged** [comment]
Ok with fuse-box@2.1.0-beta.7 it works, but there is a different error, 
```
TodoItemComponent.html:2 ERROR TypeError: this._renderer.addClass is not a function
    at MdCheckbox._setElementColor (vendor.js:71998)
    at MdCheckbox._updateColor (vendor.js:71987)
    at MdCheckbox.set [as color] (vendor.js:71977)
    at new MdCheckbox (vendor.js:71829)
    at createClass (vendor.js:42122)
    at createDirectiveInstance (vendor.js:41940)
    at createViewNodes (vendor.js:43303)
    at createEmbeddedView (vendor.js:43196)
    at callWithDebugContext (vendor.js:44423)
    at Object.debugCreateEmbeddedView [as createEmbeddedView] (vendor.js:43956)
```

**Comment by kylecordes** [comment]
It might be a while before I get back to this PR - I encourage anyone else to adopt it can work through that issue.

**Comment by nchanged** [comment]
i am pushing an update.. in 5 mins it will be there

**Comment by nchanged** [comment]
Ok, with the help of #29 it's working nicely now

**Comment by kylecordes** [comment]
great!

**Pull request closed without merging**
